# Generated by Django 4.2.21 on 2025-05-18 15:57

from django.db import migrations
import fan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_alter_customuser_options_alter_league_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', fan.models.CustomUserManager()),
            ],
        ),
    ]
