# Generated by Django 4.2.21 on 2025-05-18 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='fan.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='fan.team'),
        ),
    ]
