# Generated by Django 4.2.21 on 2025-05-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0004_alter_match_opponent_alter_match_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='fan_customuser',
        ),
        migrations.AlterModelTable(
            name='league',
            table='fan_league',
        ),
        migrations.AlterModelTable(
            name='match',
            table='fan_match',
        ),
        migrations.AlterModelTable(
            name='role',
            table='fan_role',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='fan_sport',
        ),
        migrations.AlterModelTable(
            name='team',
            table='fan_team',
        ),
        migrations.AlterModelTable(
            name='userpreference',
            table='fan_userpreference',
        ),
    ]
